//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public int id { get; set; }
        public int category_id { get; set; }
        public string sku { get; set; }
        public string img { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public int weight { get; set; }
        public string unit { get; set; }
        public int status { get; set; }
        public int quantity { get; set; }
        public int sale_price { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
    }
}
