//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public int id { get; set; }
        public string invoice_name { get; set; }
        public int total_price { get; set; }
        public int unit { get; set; }
        public int user_id { get; set; }
        public System.DateTime create_at { get; set; }
        public int status { get; set; }
        public int customer_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
    }
}
