//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INF205_ASS1_NHOM_5Entities : DbContext
    {
        public INF205_ASS1_NHOM_5Entities()
            : base("name=INF205_ASS1_NHOM_5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<invoice> invoices { get; set; }
        public DbSet<invoice_detail> invoice_detail { get; set; }
        public DbSet<product> products { get; set; }
    }
}
